hydra:
    callbacks:
        git_infos:
            _target_: hydra_callbacks.GitInfo
    run:
        dir: experiment_logs/${general.name}/train_${now:%Y%m%d_%H%M%S}
defaults:
  - _self_
  - dataset/floorplanrussia


general:
    name: DEFAULT
    device: cpu
    seed: 10
    epochs: 1
    num_workers: 6
    boundary_channels: 5
    room_channels: 7
    shuffle_type: standard
    train_batch_size: 1
    model_ckpt: null
model:
    _target_: net.DFPmodel
    boundary_channels: ${general.boundary_channels}
    room_channels: ${general.room_channels}
    interpolation_size: 512
    pretrained: true
    freeze: false
optimizer:
    optimizer_type: torch.optim.Adam
    params:
        betas:
            - 0.5
            - 0.999
        lr: 0.0001
scheduler:
    scheduler_type: torch.optim.lr_scheduler.OneCycleLR
    batch_wise_step: true
    params:
        max_lr: 0.0003
        anneal_strategy: linear
        pct_start: 0.166667
        div_factor: 10
loss:
    room_w: 1
    boundary_w: 4

logging:
    save_every_n_epochs: 5
    log_train_every_n_epochs: 25
    log_val_every_n_epochs: 1
